# Generated by Django 2.1.3 on 2018-11-10 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompteBancaire',
            fields=[
                ('num_banque', models.IntegerField(max_length=2, primary_key=True, serialize=False)),
                ('nom_banque', models.CharField(max_length=45)),
                ('cpt_banque', models.CharField(max_length=45)),
                ('date_valid_cpt', models.DateField()),
                ('date_debut_validite', models.DateField()),
                ('date_fin_validite', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseurs',
            fields=[
                ('ide_tiers', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('code_cat_socio', models.CharField(choices=[('Mltr', 'Millitaire'), ('DCG', 'Directeurs, cadres de direction et gérants'), ('PIS', 'Professions intellectuelles et scientifiques'), ('PI', 'Professions intermédiares'), ('ETA', 'Employés de type administratif'), ('PCV', 'Personnel des services directs aux particuliers, commerçants et vendeurs '), ('Cmrct', 'Agriculteurs et ouvriers qualifiés de l’agriculture, de la sylviculture et de la pêche '), ('IA', 'Métiers qualifiés de l’industrie et de l’artisanat '), ('CO', 'Conducteurs d installations et de machines et ouvriers de l’assemblage'), ('PE', 'Professions élémentaires')], max_length=5)),
                ('code_secteur', models.CharField(choices=[('AEAcS', 'Agriculteur, élevage et activités de stockage des produits d’origine végétale, animale ou halieutique'), ('AMPT', 'Activités manufacturières de production et de transformation'), ('SM', 'Extraction ou transformation de substances minérales'), ('TAI', 'Tourisme, aménagements et industries touristiques, autres activités hôtelières'), ('IndCult', 'Industries culturelles (livre, disque, cinéma, centres de documentation, centre de production audio visuelle, etc'), ('Services', 'Services exercés dans les sous - secteurs suivants: santé, éducation et formation montage et maintenance d’équipements industriels, télé - services, transports aériens et maritimes'), ('Ipaf', 'infrastructures portuaires, aéroportuaires et ferroviaires'), ('RCPZCyCa', 'réalisation de complexes commerciaux, parcs industriels, zones touristiques, cybervillages et centres artisanaux')], max_length=10)),
                ('nom_contrib', models.CharField(max_length=20)),
                ('code_typ_tiers', models.CharField(choices=[('M', 'Morale'), ('P', 'Physique')], max_length=1)),
                ('nom', models.CharField(max_length=45)),
                ('prenom', models.CharField(max_length=45)),
                ('date_fin_validite', models.DateField()),
                ('adresse', models.CharField(max_length=32)),
                ('ville', models.CharField(max_length=32)),
                ('code_postal', models.CharField(max_length=10)),
                ('boite_postal', models.CharField(max_length=10)),
                ('pays', models.CharField(max_length=32)),
                ('telephone', models.CharField(max_length=15)),
                ('date_creation', models.DateField()),
                ('compte_bancaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandats.CompteBancaire')),
            ],
        ),
        migrations.CreateModel(
            name='Mandat',
            fields=[
                ('ide_piece', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cod_statut', models.CharField(choices=[('SA', 'En saisie'), ('AC', 'Accepté'), ('VI', 'Visé'), ('RJ', 'Rejetté'), ('RF', 'Refusé'), ('RC', 'Reçu')], max_length=2)),
                ('objet', models.TextField(max_length=240)),
                ('date_emis', models.DateField()),
                ('date_reception', models.DateField()),
                ('montant', models.IntegerField()),
                ('motif_rejet', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Reglement',
            fields=[
                ('ide_reglt', models.IntegerField(primary_key=True, serialize=False)),
                ('ide_mod_reglt', models.CharField(choices=[('Vi', 'Virement'), ('Au', 'Autres')], max_length=5)),
                ('num_bank', models.CharField(max_length=32)),
                ('nom_bank', models.CharField(max_length=20)),
                ('montant', models.IntegerField()),
                ('date_ref', models.DateField()),
                ('date_echeance', models.DateField()),
                ('code_etat_reglt', models.CharField(choices=[('RG', 'Réglé')], max_length=15)),
                ('motif_incident', models.CharField(choices=[('O', 'Oui'), ('N', 'Non')], max_length=45)),
                ('compte_bancaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandats.CompteBancaire', verbose_name='référence compte bancaire')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandats.Fournisseurs', verbose_name='identifiant fournisseurs')),
                ('mandat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mandats.Mandat', verbose_name='référence mandat')),
            ],
        ),
        migrations.CreateModel(
            name='Virement',
            fields=[
                ('reference', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('typ_operation', models.CharField(max_length=3)),
                ('typ_rib_donneur', models.CharField(max_length=1)),
                ('rib_donneur', models.CharField(max_length=24)),
                ('typ_rib_beneficiaire', models.CharField(max_length=1)),
                ('rib_beneficiaire', models.CharField(max_length=24)),
                ('montant', models.IntegerField()),
                ('nom_donneur', models.CharField(max_length=35)),
                ('adresse_donneur', models.CharField(max_length=50)),
                ('date_ordre', models.DateField()),
                ('libelle', models.CharField(max_length=70)),
                ('traite', models.IntegerField(choices=[('1', 'Génération d’un paiement'), ('2', 'Envoie du paiement à la Trésorie Générale'), ('4', 'Envoie du paiement à la compensation')])),
                ('date_paiement', models.DateField()),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandats.Fournisseurs', verbose_name='références au bénéficiaire')),
                ('reglement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mandats.Reglement', verbose_name='Informations sur le réglement')),
            ],
        ),
    ]
