# Generated by Django 2.1.3 on 2018-11-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandats', '0002_auto_20181110_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reglement',
            name='ide_reglt',
        ),
        migrations.AddField(
            model_name='reglement',
            name='id_reglt',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
