# Generated by Django 2.1.3 on 2018-11-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandats', '0003_auto_20181110_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='reglement',
            name='num_reglt',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
