# Generated by Django 2.1.3 on 2018-11-17 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandats', '0004_reglement_num_reglt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virement',
            name='libelle',
        ),
        migrations.AddField(
            model_name='virement',
            name='mandat',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='mandats.Mandat'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='cod_statut',
            field=models.CharField(choices=[('SA', 'En saisie'), ('AC', 'Accepté'), ('VI', 'Visé'), ('RJ', 'Rejetté'), ('RF', 'Refusé'), ('RC', 'Reçu')], max_length=2, verbose_name='Le statut du mandat'),
        ),
        migrations.AlterField(
            model_name='mandat',
            name='motif_rejet',
            field=models.CharField(blank=True, max_length=45),
        ),
    ]
