# Generated by Django 2.1.3 on 2018-11-18 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mandats', '0005_auto_20181117_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fournisseurs',
            name='compte_bancaire',
        ),
        migrations.AddField(
            model_name='comptebancaire',
            name='fournisseur',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mandats.Fournisseurs', verbose_name='identifiant proprietaire'),
        ),
        migrations.AddField(
            model_name='mandat',
            name='fournisseur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mandats.Fournisseurs'),
        ),
        migrations.AlterField(
            model_name='virement',
            name='mandat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mandats.Mandat'),
        ),
    ]
