# Generated by Django 2.1.3 on 2018-11-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandats', '0006_auto_20181118_1338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virement',
            options={'ordering': ['date_paiement']},
        ),
    ]
