# Generated by Django 2.1.3 on 2018-11-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandats', '0008_auto_20181118_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fournisseurs',
            name='code_cat_socio',
            field=models.CharField(choices=[('Mltr', 'Millitaire'), ('DCG', 'Directeurs, cadres de direction et gérants'), ('PIS', 'Professions intellectuelles et scientifiques'), ('PI', 'Professions intermédiares'), ('ETA', 'Employés de type administratif'), ('PCV', 'Personnel des services directs aux particuliers, commerçants et vendeurs '), ('Cmrct', 'Agriculteurs et ouvriers qualifiés de l’agriculture, de la sylviculture et de la pêche '), ('IA', 'Métiers qualifiés de l’industrie et de l’artisanat '), ('CO', 'Conducteurs d installations et de machines et ouvriers de l’assemblage'), ('PE', 'Professions élémentaires')], help_text='code catégorie social', max_length=5),
        ),
    ]
