# Generated by Django 2.1.3 on 2018-11-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandats', '0010_remove_comptebancaire_date_valid_cpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virement',
            name='traite',
            field=models.IntegerField(choices=[(1, 'Génération d’un paiement'), (2, 'Envoie du paiement à la Trésorie Générale'), (4, 'Envoie du paiement à la compensation')]),
        ),
    ]
