# Generated by Django 2.1.3 on 2018-11-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandats', '0011_auto_20181120_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virement',
            name='traite',
            field=models.IntegerField(choices=[(0, 'Génération d’un paiement'), (1, 'Envoie du paiement à la Trésorie Générale'), (4, 'Envoie du paiement à la compensation')]),
        ),
    ]
