# Generated by Django 2.1.3 on 2018-11-21 18:41

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('mandats', '0012_auto_20181121_1800'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fournisseurs',
            new_name='Fournisseur',
        ),
    ]
