# Generated by Django 2.1.3 on 2018-11-21 19:05

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('mandats', '0013_auto_20181121_1841'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fournisseur',
            new_name='Fournisseurs',
        ),
    ]
