# Generated by Django 2.1.3 on 2018-11-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandats', '0015_auto_20181123_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comptebancaire',
            old_name='utiliateur',
            new_name='utilisateur',
        ),
    ]
