# Generated by Django 2.1.3 on 2018-11-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandats', '0016_auto_20181123_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fournisseurs',
            options={'ordering': ['nom']},
        ),
        migrations.AlterModelOptions(
            name='mandat',
            options={'ordering': ['ide_piece']},
        ),
    ]
