# Generated by Django 2.1.3 on 2018-11-28 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandats', '0018_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
    ]
